config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  get '/.well-known/acme-challenge/:id' => "static_pages#letsencrypt"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  namespace :api, defaults: {format: :json} do
    resources :songs, only: [:create, :update, :index, :show] do
      resources :annotations, only: [:create]
      resources :comments, only: [:create]
    end
    resources :annotations, only: [:update, :destroy]
    resources :artists, only: [:create, :show, :index, :update] do
      resources :comments, only: [:create]
    end
    resources :users, only: [:show, :update]
    resources :comments, only: [:destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnnotateMe</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="https://widget.cloudinary.com/global/all.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Ropa+Sans' rel='stylesheet' type='text/css'>
  <% if current_user %>
    <script>
      window.CURRENT_USER = <%= current_user.id %>;
      window.CURRENT_USER_EMAIL = "<%= current_user.email %>";
      window.CLOUD_NAME = "<%= ENV["CLOUD_NAME"] %>";
      window.UPLOAD_PRESET = "<%= ENV["UPLOAD_PRESET"] %>";
    </script>
  <% end %>
</head>
<body>

<% if current_user %>
<% else %>
  <%= link_to "Sign In", new_session_url %> or <%= link_to "Sign up", new_user_url %>
<% end %>

<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>